version: 2

metrics:
  - name: commits_count
    label: Commits Count
    model: ref('commits')
    description: "A count metric for commits"

    type: count
    type_params:
      count: true

    timestamp: timestamp
    time_grains: [day, week, month, year]

    dimensions:
      - author_domain
      - author_name

  - name: users_count
    label: Users Count
    model: ref('commits')
    description: "A count metric for users"

    type: count_distinct
    type_params:
      field: author_id
    sql: author_id

    timestamp: timestamp
    time_grains: [day, week, month, year]
    type_params: {}

    dimensions:
      - author_domain
